site_name: Selene Wiki
site_description: 个人刷题记录
site_url: https://pig7selene.github.io/selene_wiki/

theme:
  name: material
  language: zh
  features:
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.code.copy

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - tables
  - toc:
      permalink: true

nav:
  - 前言: index.md